language: python
python:
  - "3.6"
services:
  - postgresql
install: "pip install -r requirements.txt"
before_script:
  - psql -c 'create database web_crawler_table;' -U postgres
script: "python -m pytest"