# Generated by Django 2.1.4 on 2018-12-14 15:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('security_code', models.CharField(max_length=155, unique=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=155, null=True)),
                ('country', models.CharField(default='Indonesia', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=100, null=True), size=None)),
                ('npwp', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.CharField(blank=True, max_length=255, null=True)),
                ('ipo_date', models.DateField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=150, null=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('corporate_Secretary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('director', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
